services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7731941666:AAEgb1zKlsef7WjMfC0rD_5RnGhnZkdDg2s
    version: 3
